### ISSUE TITLE
Review #2 - Los elementos de las secciones se corren a la izquierda en modo mobile + otros se rompen.

### ISSUE THREAD

**Issue by FacundoEG** [VCamila/desafio-mod3#2]
Hola Cami como estas? primero que todo te felicito por haber enviado el desafío del modulo 3!

Te voy a sugerir / remarcar algunas cositas que estuve notando en la page

Primero que todo, fíjate que los elementos dentro de la sección uno, dos y cuatro se alinean a la izquierda cuando estas en modo mobile, te sugiero que revises eso y aproveches el usar "display:flex" o "display:grid" dentro de los contenedores padres, para que puedas acomodar mas fácilmente los contenedores hijos.

![image](https://user-images.githubusercontent.com/79592789/137131505-d68bf050-dda2-4b4f-ad5b-bb0774405f77.png)

Segundo, fíjate que entre la transición de resolución entre mobile y desktop, algunos elementos se superponen e inclusive se salen de su propio contenedor inicial:

![image](https://user-images.githubusercontent.com/79592789/137131650-d2db0bbc-8633-4a84-a890-08f455d37774.png)

![image](https://user-images.githubusercontent.com/79592789/137131629-39542ec0-44a6-48ad-9ebc-7aa0d76f58ef.png)

En resumen, te sugeriría como puse arriba, que sostengas un poco mas en usar "flex" o "grid" para ir acomodando las cosas y tengas cuidado en usar tanto margin o padding fijos para separar, ya que cuando vas cambiando la resolución al estar fijas las distancias pueden empujar o desacomodar a los demás elementos.

Te tendría que pedir entonces que revises esos temas! Ya que en modo desktop te quedo hermosa la pagina y son cositas que suelen suceder bastante!

Cualquier cosa avísame por acá o manda mensaje en el canal de discord de la carrera y te ayudamos en lo que necesites! 

Saludos!

**Comment by VCamila** [comment]
Hola, muchas gracias Facundo. Ahora veré todas las correcciones que me decís y lo vuelvo actualizar. Cualquier cosa te aviso, gracias.

**Comment by VCamila** [comment]
@FacundoEG, Buenas noches Facundo, perdón que te moleste. Quería saber como hago para que no me quede el espacio en blanco entre la imagen y el siguiente contenedor (que agregué el margin y padding en 0) en la parte de la section-uno al ver en desktop. Ahí te muestro en foto para que lo veas, gracias. 
#
![2021-10-13 (2)](https://user-images.githubusercontent.com/18042275/137226946-eba685e8-cea2-44ad-9b83-843826bcf2b9.png)

**Comment by FacundoEG** [comment]
Hola Cami! no hay problema! consultame lo que necesites.

Mira ahi volvi a entrar a la page y no me aparece que hayas hecho los cambios que tenes en la imagen, si queres hacete un push de como tenes la pagina hasta ahora así reviso bien que atributos tienen los elementos y te puedo guiar en como arreglarlo!

![image](https://user-images.githubusercontent.com/79592789/137229299-b0e0d32b-ee1d-4367-bd2a-772d9f77b7b7.png)

A simple vista puede ser que te haya quedado un padding en el contenedor padre o si estas usando flex, a veces te deja sobrantes de espacio si no les decís que hacer.

El tema es que con solamente la imagen me es difícil darte una respuesta, acordate (importante) que pongas el link de la pagina en el readme además! porque quizás si alguien mas entra a hacerte una review, te puede abrir un issue por no tener el link y se les puede complicar el ver la pagina.

Hace eso, pushea/actualiza la pagina como la tenes ahora (con el margen que me mostraste en la foto) y avísame por acá!
Yo apenas lo revise te digo bien si?

Saludos!

**Comment by VCamila** [comment]
@FacundoEG Una consulta quiero actualizar a través de la terminal y me muestra en la terminal eso en la pantalla luego de pushear, como debo seguir en este caso? Como puedo avanzar? Gracias
![2021-10-13 (3)](https://user-images.githubusercontent.com/18042275/137240142-7d43b704-f0a7-48f1-838b-9db67a5ffb1b.png)

**Comment by FacundoEG** [comment]
Hola Cami! me parece que esto sucede porque vos creaste el readme con el link y generaste cambios en el repositorio de github, por ende cuando queres pushear te avisa algo como "fijate que hiciste cambios en github y no los actualizaste antes"

Mira es un poco complejo, yo lo que te recomendaría primero que todo, es que copies el codigo con las actualizaciones nuevas que hayas hecho en una carpeta diferente a modo de "backup" (por las dudas, para que no pierdas ningun cambio nuevo)

Segundo, tenes que hacer `"git pull"` y tu codigo en vscode se va a actualizar con el readme que creaste. 

Tercero, volve a agregar el codigo que hayas cambiado con los cambios nuevos que fuiste haciendo. (si ves que solamente agrego el readme y el codigo sigue con los ultimos cambios que hiciste, obvia este paso)

Cuarto, hace un commit de los cambios y recien ahi volve a hacer `"git push"`

Una cosita, si vos ya pusiste `"git push -u origin main"` cuando creaste el repositorio y pusiste el primer commit, no hace falta que vuelvas a escribir ese comando, con poner `"git push"` alcanza y sobra.

Aca abajo por las dudas te dejo bien detallado todo:

1- Copia por las dudas el codigo que tengas ahora (con los cambios nuevos que hiciste) en una carpeta diferente a modo backup
2- Hace `"git pull"` (eso te va a traer el readme y va a "arreglar" el problema que te presenta)

(`"git pull"` puede cambiarte el codigo que ya tenes en vscode, por eso te sugeri que hagas un "backup" en otra carpeta, por las dudas. Probablemente solo te agrege el readme y listo, pero nunca esta mal ser precavidos)

3-  Una vez que hayas hecho `"git pull"`, chequea que el codigo que tenes en vscode este actualizado, si esta todo bien segui con el paso 4, si ves que te faltan cosas, usa el backup que hiciste para dejarlo como lo tenes con los cambios nuevos)

4- Commitea todo las cosas nuevas que hiciste (osea el haber traido el readme con git pull + los cambios actualizados desde que subiste el repositorio)

5- Una vez que tengas bien el commit, recien ahí manda "git push", con eso ya tendrías el repositorio actualizado y sin problemas.

Cualquier cosita escribime por aca, acordate de hacer un backup antes de iniciar los cambios desde el paso 2 y cualquier duda que tengas me avisas por aca si?

(Aca te dejo un screenshot de como se resuelve esto para que veas, si ves que en el paso final no te deja hacer push, fíjate de agregarle "-f" para que te lo "fuerze" por así decirlo)

![image](https://user-images.githubusercontent.com/79592789/137244388-d6006dba-4c09-4a13-a2ac-f058645ba9da.png)


Saludos!

**Comment by VCamila** [comment]
@FacundoEG  Hola Facundo, ya pudé gracias por su ayuda. Cualquier cosa me avisas si pudiste verlo actualizado, saludos

**Comment by FacundoEG** [comment]
Listo Cami ahí pude visualizarlo bien con los cambios!

Te comento, ese espacio en si no es un margen, es un sobrante que tiene la pagina al haberle dado un "alto" definido, como el contenedor tiene por defecto display:block, va acomodando los elementos por como los pongas por así decirlo, por ende ese espacio sobra solamente porque el alto que tiene section-one es mayor a los elementos que tienen. Osea tiene espacio sobrando en resumidas cuentas.

Eso lo podes resolver, usando display:flex y eligiendo que hacer con el espacio sobrante, o solamente quitándole el height en px a la sección, lo que lograrías que los elementos se acomoden solamente con el alto que necesitan y listo.

![image](https://user-images.githubusercontent.com/79592789/137249674-f317e298-bcc2-4b51-bbc2-87a72529c6c2.png)

Fíjate que te conviene mas! quizás display:flex te sirve mas para ir practicando ya que en un futuro se usa mucho y es mas escalable. 

Cuando tengas el desafío acomodado y todo terminado respondiendo bien, volve a enviarlo así te hacen otra review!

Cualquier otra duda me encontras por aca!

**Comment by VCamila** [comment]
Hola buenas tardes @FacundoEG gracias por su ayuda, perfecto entonces lo voy a probar y ver que onda. Lo tendré en cuenta tus consejos. Saludos, cualquier cosa te aviso por acá.

**Comment by VCamila** [comment]
Hola buenas tardes @Facundo, ya pude modificar unos pequeños detalles en la section-uno de lo que me dijiste, pero tengo un problema con la imagen de la section-dos que me fue para abajo que está en la section-tres, como lo puedo solucionarlo? Espero tu respuesta, gracias. Mil disculpas por la demora, saludos.

**Comment by FacundoEG** [comment]
Hola Cami! no pasa nada! tomate tu tiempo para resolverlo!

Mira básicamente esto te sucede porque el contenedor de section-dos no tiene definido un display especifico (osea ni siendo flex ni siendo grid). Por ende cuando no tiene espacio se "sale" del contenedor.

Acodate que los elementos si los dejas librados al azar (ósea sin decirles bien que hacer dentro de los contenedores) suelen hacer cosas extrañas, esto se puede resolver fácil usando "display:flex" o "display:grid". A lo que le estas diciendo a los elementos hijos que si o si se mantengan dentro de sus contenedores padres, ya que "controlas" como se muestran dentro del modelo de cajas.

Si no lo aclaras, van a estar en "display: block" por defecto y al no tener ancho suficiente, van a salirse del contenedor o tirarse para abajo.

![image](https://user-images.githubusercontent.com/79592789/137837016-1aac19cc-0f8f-4946-91de-3d02223641a7.png)

Cualquier otra cosita avísame! ahí te deje un screen que soluciona eso pero te dejo a vos que veas como disponerlos bien así practicas!

Te mando saludos y suerte! 

PD: Acordate de antes de entregar el desafío, de poner el link de la pagina en el readme así no te abren otro issue.

**Comment by VCamila** [comment]
Hola buenas tardes, Facundo, perfecto lo voy a modificar entonces, muchas gracias.

**Comment by VCamila** [comment]
Una consulta Facundo, en la section-dos puedo hacer con float (la imagen y el texto), en lugar de utilizar display:flex o grid se puede hacer igual? Es solo para saber si se puede hacer o no? Gracias.

**Comment by FacundoEG** [comment]
Hola Cami! mira de poder usarlo lo podes usarlo sin problema! fíjate que es diferente al uso de flex o grid. Ya que el elemento "flota" y en flex y grid los elementos se "acomodan". Son verbos diferentes, por ahora no van a hacer mucha diferencia pero quizás mas adelante te pueda traer un efecto diferente. 

De todas formas esta buenísimo que lo pruebes y veas las diferencias. Habitualmente hay muchas formas de resolver lo mismo.

Cualquier cosita avísame! saludos!

**Comment by VCamila** [comment]
Hola Facundo, sí lo probé de las dos formas. Pero lo hice con display de lo que me dijiste, me quedó mucho mejor mas que nada por los elementos. No sé si lo pudiste ver? ya esta todo ok? te pregunto para poder comenzar con el modulo 4 jajaja. Gracias. Saludos

**Comment by FacundoEG** [comment]
Hola Cami! Mira ahi lo estuve viendo y quedo mejor dispuesto!

Lo que si te recomendaría que veas, es que vos tenes el media query para desktop a los 769px, pero por ejemplo la section 2 no aguanta hasta esa resolución ya que empieza a amontonarse todo. Para que mas o menos quede bien, te tendrías que fijar que las secciones aguanten hasta los 769px de ancho asi pueden "sostenerse" dentro de ese ancho de pantalla.

Por ejemplo, aca te dejo un screen a los 800px:

![image](https://user-images.githubusercontent.com/79592789/138391799-e034cfde-bc7b-4edc-a768-14f73a31dd9b.png)

Para no hacerte problema tanto con eso, te recomiendo que los margenes de ambos elementos hijos los manejes en porcentaje, así tenes un poquito mas de control y haces que aguanten un poco mas. Si no deberías poner el media query a los 800px y tambien se solucionaria!

En las otras secciones pasa algo parecido (aproximadamente a los 1080px):

![image](https://user-images.githubusercontent.com/79592789/138391994-febe28f6-3dee-4a86-a7b8-c45b5f3f7e56.png)

Osea a opinion personal, te faltaría solo darle una repasadita y lograr que todos los elementos "aguanten" y se acomoden hasta que lleguen al punto de pasar a resolución mobile.

Estas haciendo un gran trabajo con todos esos cambios! así que no te desanimes que te falta poco para terminar.

Una vez que tengas eso, ya en teoría podrías enviar el desafío otra vez para que te lo corrijan y te lo aprueben! yo solamente estoy haciendote una review para que tengas todo dentro de todo bien y no te vuelvan a mandar un issue para que arregles algo!

Acordate, trata de que quede todo acomodado desde que inicia la resolución desktop y listo. Pero yo no te apruebo el desafío. Por ende lo vas a tener que volver a enviar cuando termines todo y ahi recíen alguien mas lo revisa y te aprueba.

Cualquier cosita preguntame, te mando un saludo y suerte!

**Comment by VCamila** [comment]
Hola Facundo, gracias por tu consejo, bueno lo voy a modificar y tendré en cuenta para adelante. Mi desafío ya fue aprobado hace una semana aprox, solo vos me recomendaste las modificaciones que venimos haciendo, por eso te pregunté si para vos ya estaba ok ya que tengo disponible el modulo 4 y el 3 aprobado. Voy a probar lo que me aconsejaste pero creo que ya no lo debo subir ya que tengo el modulo aprobado, no? o no pasa nada y puedo subirlo otra vez?
Gracias

**Comment by FacundoEG** [comment]
Aaaaaaa Camí yo pensé que no lo habías enviado! Me pone re contento si ya lo aprobaste entonces y pasaste de módulo! No hace falta que mandes más nada. Osea así como está está genial. Yo te iba dando consejos porque pensé que no lo habías aprobado y te faltaba corregir cosas!

Pero genial, como te digo seguí tranquila con el módulo 4 si? De todas formas esos cambios te ayudan a ir sumando nuevos conocimientos! 

Te mando un abrazo y te vuelvo a felicitar por haber aprobado! También te deseo suerte para el proximo módulo! Sabes que cualquier cosa podés consultar en discord y te ayudamos si? 

Saludos!

**Comment by VCamila** [comment]
Gracias, Facu, me quedó mucho mejor con lo que me dijiste del media query. Ya lo tengo todo modificado y actualizado. Gracias por tus consejos que me fueron muy útiles y los voy a tener presentes porque noté la diferencia. 
Saludos
